# Generated by Django 3.0.7 on 2020-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resourcename', models.CharField(max_length=100)),
                ('GRVM', models.TextField()),
                ('Location', models.TextField()),
                ('BGCRequest', models.TextField()),
                ('BGCInitiationDate', models.DateField()),
                ('BGCStatus', models.TextField()),
                ('ETAClosure', models.DateField()),
                ('PendingComponents', models.TextField()),
                ('ActualBGCClosureDate', models.DateField()),
                ('OnboardStatus', models.TextField()),
                ('BGCClosedAging', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('ResourceAvailableon', models.DateField()),
                ('Comments', models.TextField()),
                ('Documentreviewcomments', models.TextField()),
            ],
        ),
    ]
